sonar.projectKey=smira87_smira87_rubiks-solver
sonar.organization=smira87
sonar.host.url=https://sonarcloud.io

# Setup source and test file boundaries
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

# Reference code coverage report
sonar.go.coverage.reportPaths=coverage.out
