sonar.projectKey=smira87_rubiks-solver
sonar.organization=smira87
sonar.host.url=https://sonarcloud.io

# Path to the source and test directories
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

# Path to the Go test coverage report file
sonar.go.coverage.reportPaths=coverage.out
