jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef6142ac195e3b6d06904173eee30621b6b405e
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: '1.26.8'

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@d209202bc7d53ff1cc128f7f907dac145c9d6ae9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sarifReportPaths=sonar.sarif

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c36674332c5bfec4e5ec8755a4e1e60299c37006
        with:
          sarif_file: .scannerwork/sonar.sarif
